#!/bin/sh

DOTFILES_ROOT="`pwd`"

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_files () {
  from="$1"
  to="$2"
  success "Link '$from' to '$to'"
  rm -f "$to"
  ln -s "$from" "$to"
}

echo ''
info 'Symlinking...'
echo ''

for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
do
  dest="$HOME/.`basename \"${source%.*}\"`"

  if [ -f $dest ] || [ -d $dest ]
  then
    rm -rf $dest
    success "Removed $dest"
  fi

  link_files $source $dest
done

echo ''
info 'Symlinking... Success!'
echo ''
